language: generic

stages:
  - compile-amrex
  - compile-alamo
  - test

env:
  - DIM=2
  - DIM=3

jobs:
  include:
    - stage: compile-amrex
      script: echo "Compiling amrex now! with dim=" ${DIM} && touch amrexcompile${DIM} && ls
    - stage: compile-alamo
      script: echo "Compiling alamo now! with dim=" ${DIM} && touch alamocompile${DIM} && ls
    - stage: test
      script: echo "Testing now with dim=" ${DIM} && ls

#script: bash .hello.sh
