language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev 
  - alias g++=g++-6
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - sudo apt-get install -qq g++-6 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - cd /usr/lib/gcc/x86_64-linux-gnu/4.6
  - sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/4.8/libgfortran.a libgfortran.a
  - find /usr/lib/gcc/x86_64-linux-gnu/ -name libgfortran.a
  - mpicxx test.cpp -lgfortran

