language: generic

before_install:
  - touch before_install_${DIM} && ls
install:
  - touch install_${DIM} && ls
compile:
  - touch compile_${DIM} && ls
before_script:
  - touch before_script_${DIM} && ls
script:
  - touch script_${DIM} && ls

env:
  - DIM=one
  - DIM=two
