before_script:
  - touch before_script_${DIM} && ls
before_install:
  - touch before_install_${DIM} && ls

stages:
  - compile
  - test
  - deploy
env:
  - DIM=one
  - DIM=two
jobs:
  include:
    - stage: compile
      script: touch compile_${DIM} && ls
    - stage: deploy
      script: touch compile_${DIM} && sl

