version: 2
dependencies:
  - sudo apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev 

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: "Installing g++ 6"
          command: 'sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test &&
                    sudo apt-get update -qq &&
                    sudo apt-get install -qq g++-6  &&
                    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90 '
      - run:
          name: Compile
          command: g++ test.cpp
      - run:
          name: Run
          command: ./a.out
      - run:
          name: Print the Current Time
          command: date