version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: "C++"
          command: sudo apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev 
          command: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          command: sudo apt-get update -qq
          command: sudo apt-get install -qq g++-6 
          command: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      - run:
          name: Compile
          command: g++ test.cpp
      - run:
          name: Run
          command: ./a.out
      - run:
          name: Print the Current Time
          command: date