version: 2
dependencies:
  - sudo  

jobs:
  build2d:
    docker:
      - image: buildpack-deps:trusty 
    steps:
      - checkout
      - run:
          name: Installing preliminaries
          command: 'apt-get update && 
                    apt-get install -qq software-properties-common'
      - run:
          name: Updating compilers
          command: 'add-apt-repository -y ppa:ubuntu-toolchain-r/test &&
                    apt-get update -qq &&
                    apt-get install -qq g++-6  &&
                    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90 &&
                    apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev'
      - run:
          name: Building AMReX
          command: 'bash ./.build.amrex.sh 2'
  build3d:
    docker:
      - image: buildpack-deps:trusty 
    steps:
      - checkout
      - run:
          name: Installing preliminaries
          command: 'apt-get update && 
                    apt-get install -qq software-properties-common'
      - run:
          name: Updating compilers
          command: 'add-apt-repository -y ppa:ubuntu-toolchain-r/test &&
                    apt-get update -qq &&
                    apt-get install -qq g++-6  &&
                    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90 &&
                    apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev'
      - run:
          name: Building AMReX
          command: 'bash ./.build.amrex.sh 3'

workflows:
  version: 2
  build:
    jobs:
      - "build2d"
      - "build3d"
