version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Compile
          command: g++ test.cpp
      - run:
          name: Run
          command: ./a.out
      - run:
          name: Print the Current Time
          command: date