version: 2
dependencies:
  - sudo apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev 
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Compile
          command: g++ test.cpp
      - run:
          name: Run
          command: ./a.out
      - run:
          name: Print the Current Time
          command: date