name: Hello World with Cached Dependencies

on:
  push:
    branches-ignore:
      - "candidate-install"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }} # Pass cache info to the next job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt
            /var/lib/apt
            ~/.cache/pip
            ~/.npm
            /usr/local/lib/node_modules
          key: dependencies-${{ runner.os }}-${{ runner.image }}-${{ hashFiles('.github/workflows/dependencies.sh') }}

      - name: Install Dependencies (if needed)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          chmod +x .github/workflows/dependencies.sh
          ./.github/workflows/dependencies.sh

  run-tasks:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt
            /var/lib/apt
            ~/.cache/pip
            ~/.npm
            /usr/local/lib/node_modules
          key: dependencies-${{ runner.os }}-${{ runner.image }}-${{ hashFiles('.github/workflows/dependencies.sh') }}

      - name: Use Dependencies
        run: |
          echo "Dependencies are available!"
          python3 --version
          npm --version
