name: Cache Dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache apt dependencies
        id: apt-cache
        uses: actions/cache@v4
        with:
          path: /tmp/apt-cache
          key: apt-cache-{{ runner.os }}-{{ hashFiles('**/dependencies.sh') }}
          restore-keys: |
            apt-cache-{{ runner.os }}-

      - name: Cache pip dependencies
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-cache-{{ runner.os }}-{{ hashFiles('**/requirements.txt') }}

      - name: Cache npm dependencies
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-cache-{{ runner.os }}-{{ hashFiles('package-lock.json') }}

      - name: Run dependencies.sh script
        run: |
          chmod +x .github/workflows/dependencies.sh
          .github/workflows/dependencies.sh

  use_cache:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the "build" job and will use its cache.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore apt cache
        uses: actions/cache@v4
        with:
          path: /tmp/apt-cache
          key: apt-cache-{{ runner.os }}-{{ hashFiles('**/dependencies.sh') }}
          restore-keys: |
            apt-cache-{{ runner.os }}-

      - name: Restore pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-cache-{{ runner.os }}-{{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-cache-{{ runner.os }}-

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-cache-{{ runner.os }}-{{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-{{ runner.os }}-

      - name: Run tests (or other build steps)
        run: |
          # Add commands to run tests or other steps that require the dependencies
          echo "Using cached dependencies successfully!"
